apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-instance
  namespace: auth
spec:
  instances: 1
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-host
      value: postgres-db
    - name: db-username
      secret:
        name: postgresql-secret
        key: POSTGRES_USER
    - name: db-password
      secret:
        name: postgresql-secret
        key: POSTGRES_PASSWORD
  hostname: test.keycloak.org # patch par env
