apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
  - namespace.yaml
  - postgresql.yaml
  - instance.yaml
secretGenerator:
  - name: postgresql-secret
    literals:
      - "POSTGRES_PASSWORD=<CHANGE_ME>"
      - "POSTGRES_USER=<CHANGE_ME>"
      - "POSTGRES_DB=keycloak"
