apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton-proxy
  namespace: tekton-pipelines
spec:
  releaseName: tekton-proxy
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      clientID: "cicd-proxy"
      clientSecret: "Mx7gbE9sCX4WjCw3qawbu8bNOFRgQlHL"
      cookieSecret: "K3FmQU5GR1daVUQyOG1zMnMvNTRTTU1WWGxnd0ZEOFk="
    extraArgs:
      provider: keycloak-oidc
      redirect-url: "https://cicd.weebo.fr/oauth2/callback"
      oidc-issuer-url: "https://auth.weebo.fr/realms/main"
      ssl-upstream-insecure-skip-verify: true
      ssl-insecure-skip-verify: true
      pass-authorization-header: false
  interval: 24h
  install:
    remediation:
      retries: 3
