apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  releaseName: sonarqube
  chart:
    spec:
      chart: sonarqube
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  values:
    persistence:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      tls:
        - hosts:
            - qube.weebo.fr
          secretName: qube-weebo-tls
      hosts:
        - name: qube.weebo.fr
          path: /
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        ingress.class: nginx
  interval: 24h
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
