apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
metadata:
  name: loki
resources:
  - ../../base/LokiGrafana/namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - ../../base/LokiGrafana/
patchesStrategicMerge:
  - values.yaml
secretGenerator:
  - name: grafana-env
    literals:
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=<CHANGE_ME>"
