apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
metadata:
  name: loki
resources:
  - ../../base/LokiGrafana/namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - ../../base/LokiGrafana/
patchesStrategicMerge:
  - values.yaml
