apiVersion: v1
kind: ConfigMap
metadata:
  name: named-map
  namespace: outdns
data:
  named.conf: |
    options {
      directory "/var/cache/bind";
      listen-on port 53 { any; };
      listen-on-v6 { ::1; };
      allow-recursion {
        none;
      };
      allow-transfer {
        none;
      };
      allow-update {
        none;
      };
    };

    zone "weebo.fr." {
      type primary;
      file "/var/lib/bind/db.weebo.fr";
      notify explicit;
    };
