---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-server
  namespace: outdns
  labels:
    app: dns-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-server
  template:
    metadata:
      labels:
        app: dns-server
    spec:
      containers:
        - name: dns-server
          image: internetsystemsconsortium/bind9:9.19
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: loopback
              containerPort: 953
          volumeMounts:
            - name: named-map
              mountPath: /etc/bind
            - name: zone-map
              mountPath: /var/lib/bind/
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: dns-udp
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: zone-map
          configMap:
            name: zone-map
        - name: named-map
          configMap:
            name: named-map
