---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  namespace: outdns
  labels:
    app: dns-server
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: udo
      protocol: UDP
      port: 53
      targetPort: 53
    - name: loop
      protocol: TCP
      port: 953
      targetPort: 953
  selector:
    app: dns-server
  type: LoadBalancer
