apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  retryInterval: 5m0s
  healthChecks:
    - kind: Deployment
      name: keycloak-operator
      namespace: keycloak-operator
  prune: true
