apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
  namespace: keycloack
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      GRANT ALL PRIVILEGES ON DATABASE keycloak TO "$POSTGRES_USER";
    EOSQL
