kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kavita-config
  namespace: reader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kavita-data
  namespace: reader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
