name: build

on:
  push:
    branches:
      - "KeyCloakOpe/Main"
      - "KeyCloakOpe/dev"
      - "KeyCloakOpe/Init"

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/batleforc/keycloakope:${{ steps.vars.outputs.sha_short }}
            ghcr.io/batleforc/keycloakope:${{ steps.vars.outputs.branch }}
          # build on feature branches, push only on main branch
          push: true
