name: build

on:
  push:
    branches:
      - "KeyCloakOpe/Main"
      - "KeyCloakOpe/dev"
      - "KeyCloakOpe/Init"

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ github.sha }}-${{ github.head_ref }}"
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/batleforc/keycloakope:${{ github.sha }}
            ghcr.io/batleforc/keycloakope:${{ github.head_ref }}
          # build on feature branches, push only on main branch
          push: true
